export default {
  version: '1.0.2',
  errors: null,
  message: 'SUCCESS',
  data: [
    {
      accessToken: 'eyJhbGciOiJIUzI1NiIsImtpZCI6ImRlZmF1bHQiLCJ0eXAiOiJKV1QifQ.eyJJRCI6IjVmODJmZjU3LWZkODctNGQwOC1hZDdmLTdmMmIxN2JlOWQ0NCIsImV4cCI6MTU5MTA5NDU3OCwibmJmIjoxNTkxMDk0Mjc4LCJyb2xlcyI6WyJFTVBMT1lFRSIsIkVDT05PTUlTVCJdLCJ0eXBlIjoiYWNjZXNzIn0.wP5miUWIksMfLqprzQy8Ek4xJ9HUc-MYltLVzNKi5uE',
      refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjVmODJmZjU3LWZkODctNGQwOC1hZDdmLTdmMmIxN2JlOWQ0NCIsImV4cCI6MTU5MTA5NDg3OCwibmJmIjoxNTkxMDk0Mjc4LCJyb2xlcyI6WyJFTVBMT1lFRSIsIkVDT05PTUlTVCJdLCJ0eXBlIjoicmVmcmVzaCJ9.UVixfuLqYGItJjCJUpByM9YLQmAjC0M7MIDtcpeCGj0'
    }
  ]
}
